// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC33VMh7qjK-wiawA0ffb6y4VS2DTzw1ww',
    appId: '1:324510735442:web:d95fa05962af53b734138b',
    messagingSenderId: '324510735442',
    projectId: 'dhanra-ypfm',
    authDomain: 'dhanra-ypfm.firebaseapp.com',
    storageBucket: 'dhanra-ypfm.firebasestorage.app',
    measurementId: 'G-0RGJRVPEX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNtSLSpBpljLBKPnIOwmhyOL8K26ns-BI',
    appId: '1:324510735442:android:e9e282c5bdbf9d9134138b',
    messagingSenderId: '324510735442',
    projectId: 'dhanra-ypfm',
    storageBucket: 'dhanra-ypfm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr11QLsZfEQBFH02JrO5kL68syVi2ERMI',
    appId: '1:324510735442:ios:f7135db5d1c4315634138b',
    messagingSenderId: '324510735442',
    projectId: 'dhanra-ypfm',
    storageBucket: 'dhanra-ypfm.firebasestorage.app',
    iosBundleId: 'com.app.dhanra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr11QLsZfEQBFH02JrO5kL68syVi2ERMI',
    appId: '1:324510735442:ios:f7135db5d1c4315634138b',
    messagingSenderId: '324510735442',
    projectId: 'dhanra-ypfm',
    storageBucket: 'dhanra-ypfm.firebasestorage.app',
    iosBundleId: 'com.app.dhanra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC33VMh7qjK-wiawA0ffb6y4VS2DTzw1ww',
    appId: '1:324510735442:web:1bcfef868eb0f33e34138b',
    messagingSenderId: '324510735442',
    projectId: 'dhanra-ypfm',
    authDomain: 'dhanra-ypfm.firebaseapp.com',
    storageBucket: 'dhanra-ypfm.firebasestorage.app',
    measurementId: 'G-QNBJKZE9S9',
  );
}
